version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - app-network

  dotnet-api:
    image: mcr.microsoft.com/dotnet/aspnet:7.0
    container_name: dotnet_api_container
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=YourDatabaseName;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "5000:80"
    networks:
      - app-network
    command: dotnet YourDotNetProject.dll

volumes:
  sql_data:

networks:
  app-network:
    driver: bridge
